// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zsxkvdkamwapgvgzkmdb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpzeGt2ZGthbXdhcGd2Z3prbWRiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2NzgzMDksImV4cCI6MjA1OTI1NDMwOX0.XtH2SGaYYpGBEyNIM9vvelKLUTQSV7oveNN22y7ZSOs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);